CREATE TABLE CURSO(
  ID NUMBER(10) NOT NULL,
  CODIGO VARCHAR2(15) NOT NULL,  
  NOME VARCHAR2(30) NOT NULL,
  DESCRICAO VARCHAR2(150) NULL,
  CONSTRAINT PK_CUR_ID PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_CURSO;
