SELECT PROP.NR_ID,
       PROP.NR_ID_CURSO,
       PROP.NR_ID_INSTITUICAO,
       PROP.DS_NOME,
       PROP.DS_DESC_PROJETO,
       PROP.CD_STATUS,
       PROP.DS_REQUISITO,
       PROP.QT_PARTICIPANTES,
       PROP.NR_DURACAO,
       PROP.DS_INFO_CONTATOS,
       PROP.DS_TIPO,
       PROP.DT_GERACAO 
  FROM PROPOSTA PROP,
       (SELECT PRO.NR_ID,
               PRO.NR_ID_CURSO,
               COUNT(*) ACESSO
          FROM PROPOSTA PRO,
               LOG_ACESSO LA
         WHERE PRO.NR_ID = LA.NR_ID_PROPOSTA
        GROUP BY PRO.NR_ID,
                 PRO.NR_ID_CURSO) MAIS_ACE,
       (SELECT PR.NR_ID_CURSO,
               COUNT(*) ACESSO
          FROM LOG_ACESSO LA,
               PROPOSTA PR,
               USUARIO US
         WHERE LA.NR_ID_PROPOSTA = PR.NR_ID
           AND LA.NR_ID_USUARIO = US.NR_ID
           AND LA.NR_ID_USUARIO = &NR_ID_USUARIO
        GROUP BY PR.NR_ID_CURSO) MAIS_ACE_USU
 WHERE PROP.NR_ID = MAIS_ACE.NR_ID
   AND MAIS_ACE.DS_TIPO = MAIS_ACE_USU.DS_TIPO
ORDER BY MAIS_ACE_USU.ACESSO DESC, 
         MAIS_ACE.ACESSO DESC
