CREATE TABLE USUARIO(
  ID NUMBER(10) NOT NULL,
  EMAIL VARCHAR2(45) NOT NULL,
  SENHA VARCHAR2(30) NOT NULL,
  NOME_EXIBIDO VARCHAR2(30) NOT NULL,
  CONSTRAINT PK_USU_ID PRIMARY KEY (ID),
  CONSTRAINT UK_USU_EMAIL UNIQUE (EMAIL)
);
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE UNIVERSITARIO(
  ID NUMBER(10) NOT NULL,
  NOME VARCHAR2(30) NOT NULL,
  SOBRENOME VARCHAR2(60) NOT NULL,
  TELEFONE NUMBER(10) NULL,
  CIDADE NUMBER(10) NOT NULL,
  GRAU NUMBER(10) NOT NULL,
  CONSTRAINT PK_UNIV_ID PRIMARY KEY (ID),
  CONSTRAINT FK_UNIV_USU FOREIGN KEY (ID) REFERENCES USUARIO(ID),
  CONSTRAINT FK_UNIV_CID FOREIGN KEY (CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE INSTITUICAO(
  ID NUMBER(10) NOT NULL,
  RAZAO_SOCIAL VARCHAR2(60) NOT NULL,
  RAMO VARCHAR2(60) NOT NULL, -- Transformar em uma tabela e sugerir ramos padrões?
  CNPJ VARCHAR2(18) NOT NULL,
  CIDADE NUMBER(10) NOT NULL,
  TIPO NUMBER(10) NOT NULL, -- Transformar em uma tabela e sugerir tipos padrões?
  CONSTRAINT PK_INST_ID PRIMARY KEY (ID),
  CONSTRAINT UK_INST_CNPJ UNIQUE (CNPJ),
  CONSTRAINT FK_INST_USU FOREIGN KEY (ID) REFERENCES USUARIO(ID),
  CONSTRAINT FK_INST_CID FOREIGN KEY (CIDADE) REFERENCES CIDADE(ID)
);
