CREATE OR REPLACE FORCE VIEW VW_TEMAS_POPULARES AS
SELECT PA.*
  FROM PROPOSTA PA,
       (SELECT LA.NR_ID_PROPOSTA,
               COUNT(*) ACESSO
          FROM LOG_ACESSO LA
        GROUP BY LA.NR_ID_PROPOSTA) POPU
 WHERE PA.NR_ID = POPU.NR_ID_PROPOSTA
   AND ROWNUM <= 5
ORDER BY POPU.ACESSO DESC;
